# Application Info
spring.application.name=demomatrimony

# Server Configuration
server.port=8080

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/DemoMatrimony
spring.datasource.username=postgres
spring.datasource.password=maruf

# JPA & Hibernate Settings
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Security Configurations
app.jwt-secret=9a2f8c2e4b1a6d8e0f3c5b7a9e1d3f5a7c9b1e3f5a7c9b1e3f5a7c9b1e3f5a7c
app.jwt-expiration-milliseconds=86400000